# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Homepage

theme: dark
color: slate

useEqualHeights: true

layout:
  Hypervisor:
    header: true
    style: row
    columns: 4
  DNS:
    header: true
    style: row
    columns: 4
  Network:
    header: true
    style: row
    columns: 4
  #  Storage:
  #    header: true
  #    style: row
  #    columns: 4
  Home Automation:
    header: true
    style: row
    columns: 4
  Games Portal:
    header: true
    style: row
    columns: 4
  Games:
    header: false
    style: row
    columns: 4